### ISSUE TITLE
GUI Design and Functionality

### ISSUE THREAD

**Issue by Kavalali** [burak-yunus-softwaregroup/Car-Plate---Java#2]
Hi partner ...

I tested the code. There are some problems in design. It doesn't look right. Can you check ?

And lastly, I think you should use a JTable. It would be better to show the data in the table. I can't wait to see the pre-alpha version.

Regards.

**Comment by Meczup** [comment]
Hello...

I have good news for you. I've fixed the GUI design. I added JTable.

The added data can be viewed via JTable.

This is our pre-alpha version. I'm waiting for you to test it.

Regards.

**Comment by Kavalali** [comment]
Hi, partner.

I'm gonna test the code, and if I'm gonna let you know if I find any trouble.

I'm closing this issue.
I have new demands. Stand by for this.

Regards.
