### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by Kavalali** [burak-yunus-softwaregroup/Car-Plate---Java#4]
Hi, partner ...
I'm gonna test the code, and I'm gonna make it back to you as soon as possible.

I want to somethings from you about new version.

- You need a small function and button to save the contacts in the data base to the txt file. You can see that on the milestone page.
So I'm waiting for another button.

-And of course you need to give small messages to users. (Successfull or You have to write all information)

Waiting for their development. You know where to find me if you have a problem.

Regards

**Comment by Meczup** [comment]
Hey..

I upload new version. I did your requests.
I think, everything is okay.

Regards.
