### ISSUE TITLE
Same Record

### ISSUE THREAD

**Issue by Kavalali** [burak-yunus-softwaregroup/Car-Plate---Java#5]
Hi 
When I tested your code, I noticed something like,

I can record the same license plate more than once.
Did you forget that? Or another reason. ?

Regards

**Comment by Meczup** [comment]
Hello 
I know that. Maybe a different driver can drive another car. This so i did not use any unique id.

**Comment by Kavalali** [comment]
OK.
This part can remain so until a new request comes from users.
