### ISSUE TITLE
Update and Delete Button

### ISSUE THREAD

**Issue by Kavalali** [burak-yunus-softwaregroup/Car-Plate---Java#6]
Hi Partner ...

You didn't put the "Update-Delete" button in the program. And these are absolutely necessary.
The user may need to update and delete the information.

Will you complete these parts as soon as possible?

Regards

**Comment by Meczup** [comment]
Sorry about that..
I will update in a few munites.

**Comment by Kavalali** [comment]
Okay. I'm testing now.

**Comment by Kavalali** [comment]
Successful
